### ISSUE TITLE
2.0.4 broken!

### ISSUE THREAD

**Issue by herwarth** [irritanterik/homey-http-request-actions#22] opened 2019-01-12 23:14 UTC
cannot start the app again since updated to 2.0.4 using homey 2.0

**Comment by irritanterik** [comment] 2019-01-13 07:22
Thanks for reporting. Duplicate of #20 and #21. Fix is pending Athom approval

**Closed as completed by irritanterik** 2019-01-13 07:22 UTC

**Comment by cento007** [comment] 2019-01-13 10:08
Deze app is onverwachts gestropt. De v2.0.3 had ik werkend zonder problemen

**Comment by irritanterik** [comment] 2019-01-13 10:28
Its a known issue, I made a fix version yesterday. This fix 2.0.5 is awaiting app store apporval.

**Comment by cento007** [comment] 2019-01-13 13:05
Thanks app starts and works again!

**Comment by irritanterik** [comment] 2019-01-13 13:07
Thanks to Athom approving the update today.
